// Code generated by UniFFI. DO NOT EDIT.

package dnssec

// #include <dnssec_prover.h>
import "C"

import (
	"bytes"
	"encoding/binary"
	"fmt"
	"io"
	"math"
	"runtime"
	"sync/atomic"
	"unsafe"
)

// This is needed, because as of go 1.24
// type RustBuffer C.RustBuffer cannot have methods,
// RustBuffer is treated as non-local type
type GoRustBuffer struct {
	inner C.RustBuffer
}

type RustBufferI interface {
	AsReader() *bytes.Reader
	Free()
	ToGoBytes() []byte
	Data() unsafe.Pointer
	Len() uint64
	Capacity() uint64
}

func RustBufferFromExternal(b RustBufferI) GoRustBuffer {
	return GoRustBuffer{
		inner: C.RustBuffer{
			capacity: C.uint64_t(b.Capacity()),
			len:      C.uint64_t(b.Len()),
			data:     (*C.uchar)(b.Data()),
		},
	}
}

func (cb GoRustBuffer) Capacity() uint64 {
	return uint64(cb.inner.capacity)
}

func (cb GoRustBuffer) Len() uint64 {
	return uint64(cb.inner.len)
}

func (cb GoRustBuffer) Data() unsafe.Pointer {
	return unsafe.Pointer(cb.inner.data)
}

func (cb GoRustBuffer) AsReader() *bytes.Reader {
	b := unsafe.Slice((*byte)(cb.inner.data), C.uint64_t(cb.inner.len))
	return bytes.NewReader(b)
}

func (cb GoRustBuffer) Free() {
	rustCall(func(status *C.RustCallStatus) bool {
		C.ffi_dnssec_prover_uniffi_rustbuffer_free(cb.inner, status)
		return false
	})
}

func (cb GoRustBuffer) ToGoBytes() []byte {
	return C.GoBytes(unsafe.Pointer(cb.inner.data), C.int(cb.inner.len))
}

func stringToRustBuffer(str string) C.RustBuffer {
	return bytesToRustBuffer([]byte(str))
}

func bytesToRustBuffer(b []byte) C.RustBuffer {
	if len(b) == 0 {
		return C.RustBuffer{}
	}
	// We can pass the pointer along here, as it is pinned
	// for the duration of this call
	foreign := C.ForeignBytes{
		len:  C.int(len(b)),
		data: (*C.uchar)(unsafe.Pointer(&b[0])),
	}

	return rustCall(func(status *C.RustCallStatus) C.RustBuffer {
		return C.ffi_dnssec_prover_uniffi_rustbuffer_from_bytes(foreign, status)
	})
}

type BufLifter[GoType any] interface {
	Lift(value RustBufferI) GoType
}

type BufLowerer[GoType any] interface {
	Lower(value GoType) C.RustBuffer
}

type BufReader[GoType any] interface {
	Read(reader io.Reader) GoType
}

type BufWriter[GoType any] interface {
	Write(writer io.Writer, value GoType)
}

func LowerIntoRustBuffer[GoType any](bufWriter BufWriter[GoType], value GoType) C.RustBuffer {
	// This might be not the most efficient way but it does not require knowing allocation size
	// beforehand
	var buffer bytes.Buffer
	bufWriter.Write(&buffer, value)

	bytes, err := io.ReadAll(&buffer)
	if err != nil {
		panic(fmt.Errorf("reading written data: %w", err))
	}
	return bytesToRustBuffer(bytes)
}

func LiftFromRustBuffer[GoType any](bufReader BufReader[GoType], rbuf RustBufferI) GoType {
	defer rbuf.Free()
	reader := rbuf.AsReader()
	item := bufReader.Read(reader)
	if reader.Len() > 0 {
		// TODO: Remove this
		leftover, _ := io.ReadAll(reader)
		panic(fmt.Errorf("Junk remaining in buffer after lifting: %s", string(leftover)))
	}
	return item
}

func rustCallWithError[E any, U any](converter BufReader[*E], callback func(*C.RustCallStatus) U) (U, *E) {
	var status C.RustCallStatus
	returnValue := callback(&status)
	err := checkCallStatus(converter, status)
	return returnValue, err
}

func checkCallStatus[E any](converter BufReader[*E], status C.RustCallStatus) *E {
	switch status.code {
	case 0:
		return nil
	case 1:
		return LiftFromRustBuffer(converter, GoRustBuffer{inner: status.errorBuf})
	case 2:
		// when the rust code sees a panic, it tries to construct a rustBuffer
		// with the message.  but if that code panics, then it just sends back
		// an empty buffer.
		if status.errorBuf.len > 0 {
			panic(fmt.Errorf("%s", FfiConverterStringINSTANCE.Lift(GoRustBuffer{inner: status.errorBuf})))
		} else {
			panic(fmt.Errorf("Rust panicked while handling Rust panic"))
		}
	default:
		panic(fmt.Errorf("unknown status code: %d", status.code))
	}
}

func checkCallStatusUnknown(status C.RustCallStatus) error {
	switch status.code {
	case 0:
		return nil
	case 1:
		panic(fmt.Errorf("function not returning an error returned an error"))
	case 2:
		// when the rust code sees a panic, it tries to construct a C.RustBuffer
		// with the message.  but if that code panics, then it just sends back
		// an empty buffer.
		if status.errorBuf.len > 0 {
			panic(fmt.Errorf("%s", FfiConverterStringINSTANCE.Lift(GoRustBuffer{
				inner: status.errorBuf,
			})))
		} else {
			panic(fmt.Errorf("Rust panicked while handling Rust panic"))
		}
	default:
		return fmt.Errorf("unknown status code: %d", status.code)
	}
}

func rustCall[U any](callback func(*C.RustCallStatus) U) U {
	returnValue, err := rustCallWithError[error](nil, callback)
	if err != nil {
		panic(err)
	}
	return returnValue
}

type NativeError interface {
	AsError() error
}

func writeInt8(writer io.Writer, value int8) {
	if err := binary.Write(writer, binary.BigEndian, value); err != nil {
		panic(err)
	}
}

func writeUint8(writer io.Writer, value uint8) {
	if err := binary.Write(writer, binary.BigEndian, value); err != nil {
		panic(err)
	}
}

func writeInt16(writer io.Writer, value int16) {
	if err := binary.Write(writer, binary.BigEndian, value); err != nil {
		panic(err)
	}
}

func writeUint16(writer io.Writer, value uint16) {
	if err := binary.Write(writer, binary.BigEndian, value); err != nil {
		panic(err)
	}
}

func writeInt32(writer io.Writer, value int32) {
	if err := binary.Write(writer, binary.BigEndian, value); err != nil {
		panic(err)
	}
}

func writeUint32(writer io.Writer, value uint32) {
	if err := binary.Write(writer, binary.BigEndian, value); err != nil {
		panic(err)
	}
}

func writeInt64(writer io.Writer, value int64) {
	if err := binary.Write(writer, binary.BigEndian, value); err != nil {
		panic(err)
	}
}

func writeUint64(writer io.Writer, value uint64) {
	if err := binary.Write(writer, binary.BigEndian, value); err != nil {
		panic(err)
	}
}

func writeFloat32(writer io.Writer, value float32) {
	if err := binary.Write(writer, binary.BigEndian, value); err != nil {
		panic(err)
	}
}

func writeFloat64(writer io.Writer, value float64) {
	if err := binary.Write(writer, binary.BigEndian, value); err != nil {
		panic(err)
	}
}

func readInt8(reader io.Reader) int8 {
	var result int8
	if err := binary.Read(reader, binary.BigEndian, &result); err != nil {
		panic(err)
	}
	return result
}

func readUint8(reader io.Reader) uint8 {
	var result uint8
	if err := binary.Read(reader, binary.BigEndian, &result); err != nil {
		panic(err)
	}
	return result
}

func readInt16(reader io.Reader) int16 {
	var result int16
	if err := binary.Read(reader, binary.BigEndian, &result); err != nil {
		panic(err)
	}
	return result
}

func readUint16(reader io.Reader) uint16 {
	var result uint16
	if err := binary.Read(reader, binary.BigEndian, &result); err != nil {
		panic(err)
	}
	return result
}

func readInt32(reader io.Reader) int32 {
	var result int32
	if err := binary.Read(reader, binary.BigEndian, &result); err != nil {
		panic(err)
	}
	return result
}

func readUint32(reader io.Reader) uint32 {
	var result uint32
	if err := binary.Read(reader, binary.BigEndian, &result); err != nil {
		panic(err)
	}
	return result
}

func readInt64(reader io.Reader) int64 {
	var result int64
	if err := binary.Read(reader, binary.BigEndian, &result); err != nil {
		panic(err)
	}
	return result
}

func readUint64(reader io.Reader) uint64 {
	var result uint64
	if err := binary.Read(reader, binary.BigEndian, &result); err != nil {
		panic(err)
	}
	return result
}

func readFloat32(reader io.Reader) float32 {
	var result float32
	if err := binary.Read(reader, binary.BigEndian, &result); err != nil {
		panic(err)
	}
	return result
}

func readFloat64(reader io.Reader) float64 {
	var result float64
	if err := binary.Read(reader, binary.BigEndian, &result); err != nil {
		panic(err)
	}
	return result
}

func init() {

	uniffiCheckChecksums()
}

func uniffiCheckChecksums() {
	// Get the bindings contract version from our ComponentInterface
	bindingsContractVersion := 26
	// Get the scaffolding contract version by calling the into the dylib
	scaffoldingContractVersion := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint32_t {
		return C.ffi_dnssec_prover_uniffi_uniffi_contract_version()
	})
	if bindingsContractVersion != int(scaffoldingContractVersion) {
		// If this happens try cleaning and rebuilding your project
		panic("dnssec_prover: UniFFI contract version mismatch")
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_dnssec_prover_uniffi_checksum_func_init_proof_builder()
		})
		if checksum != 15940 {
			// If this happens try cleaning and rebuilding your project
			panic("dnssec_prover: uniffi_dnssec_prover_uniffi_checksum_func_init_proof_builder: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_dnssec_prover_uniffi_checksum_func_verify_byte_stream()
		})
		if checksum != 930 {
			// If this happens try cleaning and rebuilding your project
			panic("dnssec_prover: uniffi_dnssec_prover_uniffi_checksum_func_verify_byte_stream: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_dnssec_prover_uniffi_checksum_method_proofbuilder_get_next_query()
		})
		if checksum != 19765 {
			// If this happens try cleaning and rebuilding your project
			panic("dnssec_prover: uniffi_dnssec_prover_uniffi_checksum_method_proofbuilder_get_next_query: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_dnssec_prover_uniffi_checksum_method_proofbuilder_get_unverified_proof()
		})
		if checksum != 4620 {
			// If this happens try cleaning and rebuilding your project
			panic("dnssec_prover: uniffi_dnssec_prover_uniffi_checksum_method_proofbuilder_get_unverified_proof: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_dnssec_prover_uniffi_checksum_method_proofbuilder_process_query_response()
		})
		if checksum != 48750 {
			// If this happens try cleaning and rebuilding your project
			panic("dnssec_prover: uniffi_dnssec_prover_uniffi_checksum_method_proofbuilder_process_query_response: UniFFI API checksum mismatch")
		}
	}
}

type FfiConverterUint16 struct{}

var FfiConverterUint16INSTANCE = FfiConverterUint16{}

func (FfiConverterUint16) Lower(value uint16) C.uint16_t {
	return C.uint16_t(value)
}

func (FfiConverterUint16) Write(writer io.Writer, value uint16) {
	writeUint16(writer, value)
}

func (FfiConverterUint16) Lift(value C.uint16_t) uint16 {
	return uint16(value)
}

func (FfiConverterUint16) Read(reader io.Reader) uint16 {
	return readUint16(reader)
}

type FfiDestroyerUint16 struct{}

func (FfiDestroyerUint16) Destroy(_ uint16) {}

type FfiConverterString struct{}

var FfiConverterStringINSTANCE = FfiConverterString{}

func (FfiConverterString) Lift(rb RustBufferI) string {
	defer rb.Free()
	reader := rb.AsReader()
	b, err := io.ReadAll(reader)
	if err != nil {
		panic(fmt.Errorf("reading reader: %w", err))
	}
	return string(b)
}

func (FfiConverterString) Read(reader io.Reader) string {
	length := readInt32(reader)
	buffer := make([]byte, length)
	read_length, err := reader.Read(buffer)
	if err != nil && err != io.EOF {
		panic(err)
	}
	if read_length != int(length) {
		panic(fmt.Errorf("bad read length when reading string, expected %d, read %d", length, read_length))
	}
	return string(buffer)
}

func (FfiConverterString) Lower(value string) C.RustBuffer {
	return stringToRustBuffer(value)
}

func (FfiConverterString) Write(writer io.Writer, value string) {
	if len(value) > math.MaxInt32 {
		panic("String is too large to fit into Int32")
	}

	writeInt32(writer, int32(len(value)))
	write_length, err := io.WriteString(writer, value)
	if err != nil {
		panic(err)
	}
	if write_length != len(value) {
		panic(fmt.Errorf("bad write length when writing string, expected %d, written %d", len(value), write_length))
	}
}

type FfiDestroyerString struct{}

func (FfiDestroyerString) Destroy(_ string) {}

type FfiConverterBytes struct{}

var FfiConverterBytesINSTANCE = FfiConverterBytes{}

func (c FfiConverterBytes) Lower(value []byte) C.RustBuffer {
	return LowerIntoRustBuffer[[]byte](c, value)
}

func (c FfiConverterBytes) Write(writer io.Writer, value []byte) {
	if len(value) > math.MaxInt32 {
		panic("[]byte is too large to fit into Int32")
	}

	writeInt32(writer, int32(len(value)))
	write_length, err := writer.Write(value)
	if err != nil {
		panic(err)
	}
	if write_length != len(value) {
		panic(fmt.Errorf("bad write length when writing []byte, expected %d, written %d", len(value), write_length))
	}
}

func (c FfiConverterBytes) Lift(rb RustBufferI) []byte {
	return LiftFromRustBuffer[[]byte](c, rb)
}

func (c FfiConverterBytes) Read(reader io.Reader) []byte {
	length := readInt32(reader)
	buffer := make([]byte, length)
	read_length, err := reader.Read(buffer)
	if err != nil && err != io.EOF {
		panic(err)
	}
	if read_length != int(length) {
		panic(fmt.Errorf("bad read length when reading []byte, expected %d, read %d", length, read_length))
	}
	return buffer
}

type FfiDestroyerBytes struct{}

func (FfiDestroyerBytes) Destroy(_ []byte) {}

// Below is an implementation of synchronization requirements outlined in the link.
// https://github.com/mozilla/uniffi-rs/blob/0dc031132d9493ca812c3af6e7dd60ad2ea95bf0/uniffi_bindgen/src/bindings/kotlin/templates/ObjectRuntime.kt#L31

type FfiObject struct {
	pointer       unsafe.Pointer
	callCounter   atomic.Int64
	cloneFunction func(unsafe.Pointer, *C.RustCallStatus) unsafe.Pointer
	freeFunction  func(unsafe.Pointer, *C.RustCallStatus)
	destroyed     atomic.Bool
}

func newFfiObject(
	pointer unsafe.Pointer,
	cloneFunction func(unsafe.Pointer, *C.RustCallStatus) unsafe.Pointer,
	freeFunction func(unsafe.Pointer, *C.RustCallStatus),
) FfiObject {
	return FfiObject{
		pointer:       pointer,
		cloneFunction: cloneFunction,
		freeFunction:  freeFunction,
	}
}

func (ffiObject *FfiObject) incrementPointer(debugName string) unsafe.Pointer {
	for {
		counter := ffiObject.callCounter.Load()
		if counter <= -1 {
			panic(fmt.Errorf("%v object has already been destroyed", debugName))
		}
		if counter == math.MaxInt64 {
			panic(fmt.Errorf("%v object call counter would overflow", debugName))
		}
		if ffiObject.callCounter.CompareAndSwap(counter, counter+1) {
			break
		}
	}

	return rustCall(func(status *C.RustCallStatus) unsafe.Pointer {
		return ffiObject.cloneFunction(ffiObject.pointer, status)
	})
}

func (ffiObject *FfiObject) decrementPointer() {
	if ffiObject.callCounter.Add(-1) == -1 {
		ffiObject.freeRustArcPtr()
	}
}

func (ffiObject *FfiObject) destroy() {
	if ffiObject.destroyed.CompareAndSwap(false, true) {
		if ffiObject.callCounter.Add(-1) == -1 {
			ffiObject.freeRustArcPtr()
		}
	}
}

func (ffiObject *FfiObject) freeRustArcPtr() {
	rustCall(func(status *C.RustCallStatus) int32 {
		ffiObject.freeFunction(ffiObject.pointer, status)
		return 0
	})
}

type ProofBuilderInterface interface {
	GetNextQuery() *[]byte
	GetUnverifiedProof() *[]byte
	ProcessQueryResponse(response []byte) error
}
type ProofBuilder struct {
	ffiObject FfiObject
}

func (_self *ProofBuilder) GetNextQuery() *[]byte {
	_pointer := _self.ffiObject.incrementPointer("*ProofBuilder")
	defer _self.ffiObject.decrementPointer()
	return FfiConverterOptionalBytesINSTANCE.Lift(rustCall(func(_uniffiStatus *C.RustCallStatus) RustBufferI {
		return GoRustBuffer{
			inner: C.uniffi_dnssec_prover_uniffi_fn_method_proofbuilder_get_next_query(
				_pointer, _uniffiStatus),
		}
	}))
}

func (_self *ProofBuilder) GetUnverifiedProof() *[]byte {
	_pointer := _self.ffiObject.incrementPointer("*ProofBuilder")
	defer _self.ffiObject.decrementPointer()
	return FfiConverterOptionalBytesINSTANCE.Lift(rustCall(func(_uniffiStatus *C.RustCallStatus) RustBufferI {
		return GoRustBuffer{
			inner: C.uniffi_dnssec_prover_uniffi_fn_method_proofbuilder_get_unverified_proof(
				_pointer, _uniffiStatus),
		}
	}))
}

func (_self *ProofBuilder) ProcessQueryResponse(response []byte) error {
	_pointer := _self.ffiObject.incrementPointer("*ProofBuilder")
	defer _self.ffiObject.decrementPointer()
	_, _uniffiErr := rustCallWithError[ProofBuildingError](FfiConverterProofBuildingError{}, func(_uniffiStatus *C.RustCallStatus) bool {
		C.uniffi_dnssec_prover_uniffi_fn_method_proofbuilder_process_query_response(
			_pointer, FfiConverterBytesINSTANCE.Lower(response), _uniffiStatus)
		return false
	})
	return _uniffiErr.AsError()
}
func (object *ProofBuilder) Destroy() {
	runtime.SetFinalizer(object, nil)
	object.ffiObject.destroy()
}

type FfiConverterProofBuilder struct{}

var FfiConverterProofBuilderINSTANCE = FfiConverterProofBuilder{}

func (c FfiConverterProofBuilder) Lift(pointer unsafe.Pointer) *ProofBuilder {
	result := &ProofBuilder{
		newFfiObject(
			pointer,
			func(pointer unsafe.Pointer, status *C.RustCallStatus) unsafe.Pointer {
				return C.uniffi_dnssec_prover_uniffi_fn_clone_proofbuilder(pointer, status)
			},
			func(pointer unsafe.Pointer, status *C.RustCallStatus) {
				C.uniffi_dnssec_prover_uniffi_fn_free_proofbuilder(pointer, status)
			},
		),
	}
	runtime.SetFinalizer(result, (*ProofBuilder).Destroy)
	return result
}

func (c FfiConverterProofBuilder) Read(reader io.Reader) *ProofBuilder {
	return c.Lift(unsafe.Pointer(uintptr(readUint64(reader))))
}

func (c FfiConverterProofBuilder) Lower(value *ProofBuilder) unsafe.Pointer {
	// TODO: this is bad - all synchronization from ObjectRuntime.go is discarded here,
	// because the pointer will be decremented immediately after this function returns,
	// and someone will be left holding onto a non-locked pointer.
	pointer := value.ffiObject.incrementPointer("*ProofBuilder")
	defer value.ffiObject.decrementPointer()
	return pointer

}

func (c FfiConverterProofBuilder) Write(writer io.Writer, value *ProofBuilder) {
	writeUint64(writer, uint64(uintptr(c.Lower(value))))
}

type FfiDestroyerProofBuilder struct{}

func (_ FfiDestroyerProofBuilder) Destroy(value *ProofBuilder) {
	value.Destroy()
}

type ProofBuildingError struct {
	err error
}

// Convience method to turn *ProofBuildingError into error
// Avoiding treating nil pointer as non nil error interface
func (err *ProofBuildingError) AsError() error {
	if err == nil {
		return nil
	} else {
		return err
	}
}

func (err ProofBuildingError) Error() string {
	return fmt.Sprintf("ProofBuildingError: %s", err.err.Error())
}

func (err ProofBuildingError) Unwrap() error {
	return err.err
}

// Err* are used for checking error type with `errors.Is`
var ErrProofBuildingErrorInvalidResponse = fmt.Errorf("ProofBuildingErrorInvalidResponse")
var ErrProofBuildingErrorServerFailure = fmt.Errorf("ProofBuildingErrorServerFailure")
var ErrProofBuildingErrorNoSuchName = fmt.Errorf("ProofBuildingErrorNoSuchName")
var ErrProofBuildingErrorMissingRecord = fmt.Errorf("ProofBuildingErrorMissingRecord")
var ErrProofBuildingErrorUnauthenticated = fmt.Errorf("ProofBuildingErrorUnauthenticated")
var ErrProofBuildingErrorNoResponseExpected = fmt.Errorf("ProofBuildingErrorNoResponseExpected")

// Variant structs
type ProofBuildingErrorInvalidResponse struct {
	message string
}

func NewProofBuildingErrorInvalidResponse() *ProofBuildingError {
	return &ProofBuildingError{err: &ProofBuildingErrorInvalidResponse{}}
}

func (e ProofBuildingErrorInvalidResponse) destroy() {
}

func (err ProofBuildingErrorInvalidResponse) Error() string {
	return fmt.Sprintf("InvalidResponse: %s", err.message)
}

func (self ProofBuildingErrorInvalidResponse) Is(target error) bool {
	return target == ErrProofBuildingErrorInvalidResponse
}

type ProofBuildingErrorServerFailure struct {
	message string
}

func NewProofBuildingErrorServerFailure() *ProofBuildingError {
	return &ProofBuildingError{err: &ProofBuildingErrorServerFailure{}}
}

func (e ProofBuildingErrorServerFailure) destroy() {
}

func (err ProofBuildingErrorServerFailure) Error() string {
	return fmt.Sprintf("ServerFailure: %s", err.message)
}

func (self ProofBuildingErrorServerFailure) Is(target error) bool {
	return target == ErrProofBuildingErrorServerFailure
}

type ProofBuildingErrorNoSuchName struct {
	message string
}

func NewProofBuildingErrorNoSuchName() *ProofBuildingError {
	return &ProofBuildingError{err: &ProofBuildingErrorNoSuchName{}}
}

func (e ProofBuildingErrorNoSuchName) destroy() {
}

func (err ProofBuildingErrorNoSuchName) Error() string {
	return fmt.Sprintf("NoSuchName: %s", err.message)
}

func (self ProofBuildingErrorNoSuchName) Is(target error) bool {
	return target == ErrProofBuildingErrorNoSuchName
}

type ProofBuildingErrorMissingRecord struct {
	message string
}

func NewProofBuildingErrorMissingRecord() *ProofBuildingError {
	return &ProofBuildingError{err: &ProofBuildingErrorMissingRecord{}}
}

func (e ProofBuildingErrorMissingRecord) destroy() {
}

func (err ProofBuildingErrorMissingRecord) Error() string {
	return fmt.Sprintf("MissingRecord: %s", err.message)
}

func (self ProofBuildingErrorMissingRecord) Is(target error) bool {
	return target == ErrProofBuildingErrorMissingRecord
}

type ProofBuildingErrorUnauthenticated struct {
	message string
}

func NewProofBuildingErrorUnauthenticated() *ProofBuildingError {
	return &ProofBuildingError{err: &ProofBuildingErrorUnauthenticated{}}
}

func (e ProofBuildingErrorUnauthenticated) destroy() {
}

func (err ProofBuildingErrorUnauthenticated) Error() string {
	return fmt.Sprintf("Unauthenticated: %s", err.message)
}

func (self ProofBuildingErrorUnauthenticated) Is(target error) bool {
	return target == ErrProofBuildingErrorUnauthenticated
}

type ProofBuildingErrorNoResponseExpected struct {
	message string
}

func NewProofBuildingErrorNoResponseExpected() *ProofBuildingError {
	return &ProofBuildingError{err: &ProofBuildingErrorNoResponseExpected{}}
}

func (e ProofBuildingErrorNoResponseExpected) destroy() {
}

func (err ProofBuildingErrorNoResponseExpected) Error() string {
	return fmt.Sprintf("NoResponseExpected: %s", err.message)
}

func (self ProofBuildingErrorNoResponseExpected) Is(target error) bool {
	return target == ErrProofBuildingErrorNoResponseExpected
}

type FfiConverterProofBuildingError struct{}

var FfiConverterProofBuildingErrorINSTANCE = FfiConverterProofBuildingError{}

func (c FfiConverterProofBuildingError) Lift(eb RustBufferI) *ProofBuildingError {
	return LiftFromRustBuffer[*ProofBuildingError](c, eb)
}

func (c FfiConverterProofBuildingError) Lower(value *ProofBuildingError) C.RustBuffer {
	return LowerIntoRustBuffer[*ProofBuildingError](c, value)
}

func (c FfiConverterProofBuildingError) Read(reader io.Reader) *ProofBuildingError {
	errorID := readUint32(reader)

	message := FfiConverterStringINSTANCE.Read(reader)
	switch errorID {
	case 1:
		return &ProofBuildingError{&ProofBuildingErrorInvalidResponse{message}}
	case 2:
		return &ProofBuildingError{&ProofBuildingErrorServerFailure{message}}
	case 3:
		return &ProofBuildingError{&ProofBuildingErrorNoSuchName{message}}
	case 4:
		return &ProofBuildingError{&ProofBuildingErrorMissingRecord{message}}
	case 5:
		return &ProofBuildingError{&ProofBuildingErrorUnauthenticated{message}}
	case 6:
		return &ProofBuildingError{&ProofBuildingErrorNoResponseExpected{message}}
	default:
		panic(fmt.Sprintf("Unknown error code %d in FfiConverterProofBuildingError.Read()", errorID))
	}

}

func (c FfiConverterProofBuildingError) Write(writer io.Writer, value *ProofBuildingError) {
	switch variantValue := value.err.(type) {
	case *ProofBuildingErrorInvalidResponse:
		writeInt32(writer, 1)
	case *ProofBuildingErrorServerFailure:
		writeInt32(writer, 2)
	case *ProofBuildingErrorNoSuchName:
		writeInt32(writer, 3)
	case *ProofBuildingErrorMissingRecord:
		writeInt32(writer, 4)
	case *ProofBuildingErrorUnauthenticated:
		writeInt32(writer, 5)
	case *ProofBuildingErrorNoResponseExpected:
		writeInt32(writer, 6)
	default:
		_ = variantValue
		panic(fmt.Sprintf("invalid error value `%v` in FfiConverterProofBuildingError.Write", value))
	}
}

type FfiDestroyerProofBuildingError struct{}

func (_ FfiDestroyerProofBuildingError) Destroy(value *ProofBuildingError) {
	switch variantValue := value.err.(type) {
	case ProofBuildingErrorInvalidResponse:
		variantValue.destroy()
	case ProofBuildingErrorServerFailure:
		variantValue.destroy()
	case ProofBuildingErrorNoSuchName:
		variantValue.destroy()
	case ProofBuildingErrorMissingRecord:
		variantValue.destroy()
	case ProofBuildingErrorUnauthenticated:
		variantValue.destroy()
	case ProofBuildingErrorNoResponseExpected:
		variantValue.destroy()
	default:
		_ = variantValue
		panic(fmt.Sprintf("invalid error value `%v` in FfiDestroyerProofBuildingError.Destroy", value))
	}
}

type FfiConverterOptionalBytes struct{}

var FfiConverterOptionalBytesINSTANCE = FfiConverterOptionalBytes{}

func (c FfiConverterOptionalBytes) Lift(rb RustBufferI) *[]byte {
	return LiftFromRustBuffer[*[]byte](c, rb)
}

func (_ FfiConverterOptionalBytes) Read(reader io.Reader) *[]byte {
	if readInt8(reader) == 0 {
		return nil
	}
	temp := FfiConverterBytesINSTANCE.Read(reader)
	return &temp
}

func (c FfiConverterOptionalBytes) Lower(value *[]byte) C.RustBuffer {
	return LowerIntoRustBuffer[*[]byte](c, value)
}

func (_ FfiConverterOptionalBytes) Write(writer io.Writer, value *[]byte) {
	if value == nil {
		writeInt8(writer, 0)
	} else {
		writeInt8(writer, 1)
		FfiConverterBytesINSTANCE.Write(writer, *value)
	}
}

type FfiDestroyerOptionalBytes struct{}

func (_ FfiDestroyerOptionalBytes) Destroy(value *[]byte) {
	if value != nil {
		FfiDestroyerBytes{}.Destroy(*value)
	}
}

type FfiConverterOptionalProofBuilder struct{}

var FfiConverterOptionalProofBuilderINSTANCE = FfiConverterOptionalProofBuilder{}

func (c FfiConverterOptionalProofBuilder) Lift(rb RustBufferI) **ProofBuilder {
	return LiftFromRustBuffer[**ProofBuilder](c, rb)
}

func (_ FfiConverterOptionalProofBuilder) Read(reader io.Reader) **ProofBuilder {
	if readInt8(reader) == 0 {
		return nil
	}
	temp := FfiConverterProofBuilderINSTANCE.Read(reader)
	return &temp
}

func (c FfiConverterOptionalProofBuilder) Lower(value **ProofBuilder) C.RustBuffer {
	return LowerIntoRustBuffer[**ProofBuilder](c, value)
}

func (_ FfiConverterOptionalProofBuilder) Write(writer io.Writer, value **ProofBuilder) {
	if value == nil {
		writeInt8(writer, 0)
	} else {
		writeInt8(writer, 1)
		FfiConverterProofBuilderINSTANCE.Write(writer, *value)
	}
}

type FfiDestroyerOptionalProofBuilder struct{}

func (_ FfiDestroyerOptionalProofBuilder) Destroy(value **ProofBuilder) {
	if value != nil {
		FfiDestroyerProofBuilder{}.Destroy(*value)
	}
}

func InitProofBuilder(name string, ty uint16) **ProofBuilder {
	return FfiConverterOptionalProofBuilderINSTANCE.Lift(rustCall(func(_uniffiStatus *C.RustCallStatus) RustBufferI {
		return GoRustBuffer{
			inner: C.uniffi_dnssec_prover_uniffi_fn_func_init_proof_builder(FfiConverterStringINSTANCE.Lower(name), FfiConverterUint16INSTANCE.Lower(ty), _uniffiStatus),
		}
	}))
}

func VerifyByteStream(stream []byte, nameToResolve string) string {
	return FfiConverterStringINSTANCE.Lift(rustCall(func(_uniffiStatus *C.RustCallStatus) RustBufferI {
		return GoRustBuffer{
			inner: C.uniffi_dnssec_prover_uniffi_fn_func_verify_byte_stream(FfiConverterBytesINSTANCE.Lower(stream), FfiConverterStringINSTANCE.Lower(nameToResolve), _uniffiStatus),
		}
	}))
}
